config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  root 'dashboard#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    has_one :answer

    def check_avalibilty_of_question
      greetings = ["HI", "hi", "Hi", "Hiee", "hiee", "hie", "HELLO", "hello", "howdy", "HOWDY", "kem cho"]
      if greetings.any? { |w| 
          @string = self.question[w] 
        }
        if @string
          @question = Question.where(question: @string.downcase).first
          answer = @question.answer
        else
          answer = Answer.first.answer
        end
      else
        answer = Answer.first.answer
      end  
      return answer
    end
end

app/models/question_session.rb
class QuestionSession
  def initialize(session)
    @session = session
    @session[:question_id] ||= []
  end
  
  def add_to_list(guest_question)
    @session[:question_id] << guest_question.id
  end
  
  def remove_from_list(guest_question)
    @session.delete(guest_question.id)
  end
  
  def current_questions
    @session[:question_id]
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  def index
    @answers = Answer.all
  end

  def show
  end

  def new
    @answer = Answer.new
  end

  def edit
  end

  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:question_id, :answer)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :question_session

  def question_session
    @question_session ||= QuestionSession.new(session)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    if question_session.current_questions
      @questions = Question.where('id IN (?)', question_session.current_questions).order('id DESC')
      
      @questions.each do |question|
        if question.created_at <= Time.zone.now - 5*60
          question_session.remove_from_list(question)
        end
      end
    end
    @question = Question.new
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = Question.new(question_params)

    #answer = @question.check_avalibilty_of_question
    respond_to do |format|
      if @question.save
        question_session.add_to_list(@question)
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:question)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.text_field :question_id, id: :answer_question_id %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer, id: :answer_answer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.question %></td>
        <td><%= answer.answer %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @answer.answer %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/dashboard/index.html.erb
<script type="text/javascript">
  var accessToken = "f98d27910f1d47208e89561839f87fdc",
    baseUrl = "https://api.api.ai/v1/",
    $speechInput,
    $recBtn,
    recognition,
    messageRecording = "Recording...",
    messageCouldntHear = "I couldn't hear you, could you say that again?",
    messageInternalError = "Oh no, there has been an internal server error",
    messageSorry = "I'm sorry, I don't have the answer to that yet.";

  $(document).ready(function() {
    $speechInput = $("#speech");
    $recBtn = $("#rec");

    $speechInput.keypress(function(event) {
      if (event.which == 13) {
        event.preventDefault();
        send();
      }
    });
    $recBtn.on("click", function(event) {
      switchRecognition();
    });
    $(".debug__btn").on("click", function() {
      $(this).next().toggleClass("is-active");
      return false;
    });
  });

  function startRecognition() {
    recognition = new webkitSpeechRecognition();
    recognition.continuous = false;
        recognition.interimResults = false;

    recognition.onstart = function(event) {
      respond(messageRecording);
      updateRec();
    };
    recognition.onresult = function(event) {
      recognition.onend = null;
      
      var text = "";
        for (var i = event.resultIndex; i < event.results.length; ++i) {
          text += event.results[i][0].transcript;
        }
        setInput(text);
      stopRecognition();
    };
    recognition.onend = function() {
      respond(messageCouldntHear);
      stopRecognition();
    };
    recognition.lang = "en-US";
    recognition.start();
  }

  function stopRecognition() {
    if (recognition) {
      recognition.stop();
      recognition = null;
    }
    updateRec();
  }

  function switchRecognition() {
    if (recognition) {
      stopRecognition();
    } else {
      startRecognition();
    }
  }

  function setInput(text) {
    $speechInput.val(text);
    send();
  }

  function updateRec() {
    $recBtn.text(recognition ? "Stop" : "Speak");
  }

  function send() {
    var text = $speechInput.val();
    $.ajax({
      type: "POST",
      url: baseUrl + "query",
      contentType: "application/json; charset=utf-8",
      dataType: "json",
      headers: {
        "Authorization": "Bearer " + accessToken
      },
      data: JSON.stringify({query: text, lang: "en", sessionId: "yaydevdiner"}),

      success: function(data) {
        prepareResponse(data);
      },
      error: function() {
        respond(messageInternalError);
      }
    });
  }

  function prepareResponse(val) {
    var debugJSON = JSON.stringify(val, undefined, 2),
      spokenResponse = val.result.speech;

    respond(spokenResponse);
    debugRespond(debugJSON);
  }

  function debugRespond(val) {
    $("#response").text(val);
  }

  function respond(val) {
    if (val == "") {
      val = messageSorry;
    }

    if (val !== messageRecording) {
      var msg = new SpeechSynthesisUtterance();
      msg.voiceURI = "native";
      msg.text = val;
      msg.lang = "en-US";
      window.speechSynthesis.speak(msg);
    }

    $("#spokenResponse").addClass("is-active").find(".spoken-response__text").html(val);
  }

  var chart = AmCharts.makeChart("chartdiv", {
      "type": "xy",
      "theme": "dark",
      "marginRight": 80,
      "dataDateFormat": "YYYY-MM-DD",
      "startDuration": 1.5,
      "trendLines": [],
      "balloon": {
          "adjustBorderColor": false,
          "shadowAlpha": 0,
          "fixedPosition":true
      },
      "graphs": [{
          "balloonText": "<div style='margin:5px;'><b>[[x]]</b><br>y:<b>[[y]]</b><br>value:<b>[[value]]</b></div>",
          "bullet": "round",
          "id": "AmGraph-1",
          "lineAlpha": 0,
          "lineColor": "#b0de09",
          "fillAlphas": 0,
          "valueField": "aValue",
          "xField": "date",
          "yField": "ay"
      }, {
          "balloonText": "<div style='margin:5px;'><b>[[x]]</b><br>y:<b>[[y]]</b><br>value:<b>[[value]]</b></div>",
          "bullet": "round",
          "id": "AmGraph-2",
          "lineAlpha": 0,
          "lineColor": "#fcd202",
          "fillAlphas": 0,
          "valueField": "bValue",
          "xField": "date",
          "yField": "by"
      }],
      "valueAxes": [{
          "id": "ValueAxis-1",
          "axisAlpha": 0
      }, {
          "id": "ValueAxis-2",
          "axisAlpha": 0,
          "position": "bottom",
          "type": "date",
          "minimumDate": new Date(2014, 11, 31),
          "maximumDate": new Date(2015, 0, 13)
      }],
      "allLabels": [],
      "titles": [],
      "dataProvider": [{
          "date": "2015-01-01",
          "ay": 6.5,
          "by": 2.2,
          "aValue": 15,
          "bValue": 10
      }, {
          "date": "2015-01-02",
          "ay": 12.3,
          "by": 4.9,
          "aValue": 8,
          "bValue": 3
      }, {
          "date": "2015-01-03",
          "ay": 12.3,
          "by": 5.1,
          "aValue": 16,
          "bValue": 4
      }, {
          "date": "2015-01-04",
          "ay": 2.8,
          "by": 13.3,
          "aValue": 9,
          "bValue": 13
      }, {
          "date": "2015-01-05",
          "ay": 3.5,
          "by": 6.1,
          "aValue": 5,
          "bValue": 2
      }, {
          "date": "2015-01-06",
          "ay": 5.1,
          "by": 8.3,
          "aValue": 10,
          "bValue": 17
      }, {
          "date": "2015-01-07",
          "ay": 6.7,
          "by": 10.5,
          "aValue": 3,
          "bValue": 10
      }, {
          "date": "2015-01-08",
          "ay": 8,
          "by": 12.3,
          "aValue": 5,
          "bValue": 13
      }, {
          "date": "2015-01-09",
          "ay": 8.9,
          "by": 4.5,
          "aValue": 8,
          "bValue": 11
      }, {
          "date": "2015-01-10",
          "ay": 9.7,
          "by": 15,
          "aValue": 15,
          "bValue": 10
      }, {
          "date": "2015-01-11",
          "ay": 10.4,
          "by": 10.8,
          "aValue": 1,
          "bValue": 11
      }, {
          "date": "2015-01-12",
          "ay": 1.7,
          "by": 19,
          "aValue": 12,
          "bValue": 3
      }],

      "export": {
          "enabled": true
      },

      "chartScrollbar": {
          "offset": 15,
          "scrollbarHeight": 5
      },

      "chartCursor":{
         "pan":true,
         "cursorAlpha":0,
         "valueLineAlpha":0
      }
  });

</script>
<div class="row">
  <div id="chartdiv"></div>
  <div class="container centered">
    <div class="col-xs-12 col-md-6">
      <input id="speech" type="text">
      <button id="rec" class="btn">Speak</button>
      <div id="spokenResponse" class="spoken-response">
        <div class="spoken-response__text"></div>
      </div>  
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jerry</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
    <script src="https://www.amcharts.com/lib/3/xy.js"></script>
    <script src="https://www.amcharts.com/lib/3/themes/dark.js"></script>
    <script src="https://www.amcharts.com/lib/3/plugins/export/export.min.js"></script>
    <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question, id: :question_question %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.question %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>